@startuml
skinparam shadowing false
title Fluxo Atual - Operacao do Galpao (AS-IS)

start

:Mapeamento das escolas;
:Contagem e conferencia manual dos produtos;
:Registro fotografico da conferencia;
:Anexacao das fotos no Trello;
:Validacao da conferencia;
:Solicitacao do transporte;

if (Rota definida?) then (sim)
  :Disponibilizacao da demanda ao motorista;
  :Inicio do percurso;
  :Execucao da rota pre-determinada;
  :Conclusao do transporte;
  
  if (Entrega realizada?) then (sim)
    :Finalizacao normal;
  else (nao)
    :Identificacao de entregas nao realizadas;
    :Conferencia das notas fiscais do dia anterior;
    :Registro das pendencias no Trello;
    :Transicao para o expediente seguinte;
  endif
  
else (nao)
  :Retirada direta do material no galpao;
  :Atualizacao do status no Trello;
endif

:Elaboracao do relatorio semestral;
:Arquivamento e fechamento do periodo;

stop
@enduml